server:
  port: 8081
logging:
  config: classpath:logback-spring.xml
spring:
  application:
    name: rpc-client

rpc:
  client:
      zk:
        root: /rpc
        addr: 10.10.20.111:2181,10.10.20.112:2181,10.10.20.113:2181
        switch: true
        timeout: 10000
      api:
        package: com.itcast.rpc.api
  cluster:
        strategy: Polling