server:
  port: 8080


spring:
#指定缓存的类型
  cache:
    type: redis


  redis:
    password: 123456

#指定redis底层客户端实现
    client-type: lettuce

    lettuce:
      pool:
# 连接池最大连接数（使用负值表示没有限制）
        max-active: 10

# 连接池中的最大空闲连接
        max-idle: 10

# 连接池中的最小空闲连接
        min-idle: 0
# 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
#    sentinel:
#      master: mymaster
#      nodes: 8.129.113.233:26379,8.129.113.233:26380,8.129.113.233:26381
    cluster:
    #命令最多转发次数
      max-redirects: 3
      nodes: 8.129.113.23:6381,8.129.113.33:6382,8.129.113.43:6383,8.129.113.53:6384,8.129.113.63:6385,8.129.113.73:6386
#
#    jedis:
#      pool:
## 连接池最大连接数（使用负值表示没有限制）
#        max-active: 10
#
## 连接池中的最大空闲连接
#        max-idle: 10
#
## 连接池中的最小空闲连接
#        min-idle: 0
## 连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-wait: -1ms



#==============================数据库相关配置========================================
#数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/redis?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: lucien@1234

#配置plus打印sql日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl